spring:
  config:
    activate:
      on-profile: default,development
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: hexa.unist.no.reply@gmail.com
    password: zarbehcegbirkwzk
    default-encoding: UTF-8
    smtp:
      start-tls-enable: true
      auth: true
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    vault:
      enabled: true
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: kv
        application-name: homepage/backend/production
      uri: http://vault.hexa.pro
  mail:
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    protocol: ${spring.mail.protocol}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    default-encoding: ${spring.mail.default-encoding}
    smtp:
      start-tls-enable: ${spring.mail.smtp.start-tls-enable}
      auth: ${spring.mail.smtp.auth}
