spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: hexa.admin@gmail.com
    password: 1111111
    default-encoding: UTF-8
    smtp:
      start-tls-enable: true
      auth: true
