version: 0.0.1
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: default,development
  redis:
    host: localhost
    port: 6379
    password: "ta,TvT5P]ox<Ho0vs"
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
hexa-page-jwt-secret-key: HexaH0mePageBack
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    vault:
      enabled: true
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: kv
        application-name: homepage/backend/production
      uri: http://vault.hexa.pro
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
  mvc:
    pathmatch:
      matching-strategy: ${spring.mvc.pathmatch.matching-strategy}
  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
logging:
  level:
    org.hibernate.SQL: ${logging.level.org.hibernate.SQL}
    org.hibernate.type: ${logging.level.org.hibernate.type}
hexa-page-jwt-secret-key: ${hexa-page-jwt-secret-key}
