name: Deployment

concurrency: production

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux]


    steps:

      - uses: actions/checkout@v4

      - name: stop and remove the previous container
        run: |
          docker stop ${{HeXA_Homepage_Backend_Container_Name}}
          docker container rm ${{HeXA_Homepage_Backend_Container_Name}}

      - name: generate docker container name
        run: export HeXA_Homepage_Backend_Container_Name=HeXA_Homepage_Backend:${GITHUB_REF#refs/tags/}

      - name: build docker image
        env:
          Vault_Token: ${{ secrets.VAULT_TOKEN }}
        run: docker build . --file dockerfile -t HeXA_Homepage_Backend:${GITHUB_REF#refs/tags/} --build-arg VAULT_TOKEN=${{Vault_Token}}

      - name: run and test
        run: |
          docker run -d -p 8282:8080 --name ${{HeXA_Homepage_Backend_Container_Name}}
          test_result="$(docker exec ${{HeXA_Homepage_Backend_Container_Name}} ./gradlew test)"
          second_last_line="$(echo "$log_content" | tail -n 2 | head -n 1)"
          
          if [[ "$second_last_line" == "BUILD SUCCESSFUL"* ]]; then
            echo "TEST SUCCESSFUL"
          else
            docker stop ${{HeXA_Homepage_Backend_Container_Name}}
            docker container rm ${{HeXA_Homepage_Backend_Container_Name}}
            last_version=$(docker images | grep 'hompage_test' | awk '{print $2}' | tail -n 2 | head -n 1)
            docker run -d -p 8282:8080 --name ${{HeXA_Homepage_Backend_Container_Name}}:$last_version
            echo "TEST FAILED"
          fi


