name: hello

on:
  push:
    - main

jobs:
  test:
    name: why name again?
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: why
        run: ls

      - name: make text file
        run: echo "good with tags" >> by_the_test_action.txt

      - name: maybe new line?
        run: |
          echo "good with tags" >> by_the_test_action.txt